# Generated by Django 4.2 on 2026-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
